inherit_from: .rubocop_todo.yml
#require: rubocop-rspec

AllCops:
  NewCops: enable
  Include:
    - 'lib/**/*'
  Exclude:
    - Gemfile
    - Rakefile
    - '*.gemspec'
    - 'tmp/**'
    - 'lib/saharspec/matchers/request_webmock.rb'
  DisplayCopNames: true
  TargetRubyVersion: 2.7

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Naming/PredicateName:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Layout/LineLength:
  Max: 100
  IgnoredPatterns: ['\#.*'] # ignore long comments

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: '{}'

Style/AndOr:
  EnforcedStyle: conditionals

Style/Documentation:
  Enabled: false

Style/SignalException:
  EnforcedStyle: semantic

Style/FormatStringToken:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false

Style/CaseEquality:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

# Should always be configured:
Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Metrics/AbcSize:
  Max: 30
